# validate this file at http://lint.travis-ci.org/
# ocaml and coq are not on the list of languages:
language:       generic
sudo: 		required
# "trusty" is the most modern release of Ubuntu supported
dist: 		trusty
git:
  submodules:   false
services:
  - docker
# build coqide along with the Tactics package, just because it's a short package
env:
  - PACKAGES="Foundations Combinatorics Algebra NumberSystems PAdics"
  - PACKAGES=CategoryTheory
  - PACKAGES="MoreFoundations Ktheory"
  - PACKAGES=HomologicalAlgebra
  - PACKAGES=Topology
  - PACKAGES=RealNumbers
  - PACKAGES=SubstitutionSystems
  - PACKAGES=Tactics BUILD_COQIDE=yes BUILD_ALSO=TAGS
  - PACKAGES=Folds
  - FOUNDATIONS_CHANGE_ERROR=yes BUILD_ALSO="check-for-change-to-Foundations enforce-listing-of-proof-files"
# building Coq in a separate stage folds up the output in the log:
before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ocaml/ocaml:ubuntu-17.10 tail -f /dev/null
  - docker ps
install:
  - docker exec -t ubuntu-test bash -c "
    apt-get update;
    apt-get install -y emacs coq coqide
    "
script:
  - docker exec -t ubuntu-test bash -c "
    cd /travis;
    time make TIMECMD=time BUILD_COQ=no $PACKAGES $BUILD_ALSO FOUNDATIONS_CHANGE_ERROR=$FOUNDATIONS_CHANGE_ERROR
    "
